module.exports = {
  someSidebar: {
    Coursebook: [
      {
        type: "category",
        label: "Week 1",
        items: [
          "Week 01/README",
          {
            type: "category",
            label: "Session 0",
            items: [
              "Week 01/session-00/README",
              "Week 01/session-00/intro-to-web",
              "Week 01/session-00/programming",
              "Week 01/session-00/resources",
              "Week 01/session-00/webdev-tools",
            ],
          },
          {
            type: "category",
            label: "Session 1",
            items: [
              "Week 01/session-01/README",
              "Week 01/session-01/elements-and-attributes",
              "Week 01/session-01/exercise",
              "Week 01/session-01/intro-to-html",
              "Week 01/session-01/learning-outcomes",
              "Week 01/session-01/research-topics",
              "Week 01/session-01/resources",
            ],
          },
          {
            type: "category",
            label: "Session 2",
            items: [
              "Week 01/session-02/README",
              "Week 01/session-02/intro-to-github",
              "Week 01/session-02/introduction-to-git",
            ],
          },
        ],
      },
      {
        type: "category",
        label: "Week 2",
        items: [
          "Week 02/README",
          {
            type: "category",
            label: "Session 3",
            items: [
              "Week 02/session-03/README",
              "Week 02/session-03/assignment",
              "Week 02/session-03/exercise",
              "Week 02/session-03/learning-outcomes",
              "Week 02/session-03/resources",
              "Week 02/session-03/table-form",
              "Week 02/session-03/topic",
            ],
          },
          {
            type: "category",
            label: "Session 4",
            items: [
              "Week 02/session-04/README",
              "Week 02/session-04/exercise",
              "Week 02/session-04/introAndSelectors",
              "Week 02/session-04/learning-outcomes",
              "Week 02/session-04/pseudoClassAndElement",
              "Week 02/session-04/research-topics",
              "Week 02/session-04/resources",
              "Week 02/session-04/typesOfStyles",
            ],
          },
          {
            type: "category",
            label: "Session 4",
            items: [
              "Week 02/session-04/README",
              "Week 02/session-04/exercise",
              "Week 02/session-04/introAndSelectors",
              "Week 02/session-04/learning-outcomes",
              "Week 02/session-04/pseudoClassAndElement",
              "Week 02/session-04/research-topics",
              "Week 02/session-04/resources",
              "Week 02/session-04/typesOfStyles",
            ],
          },
          {
            type: "category",
            label: "Session 5",
            items: [
              "Week 02/session-05/Cascading",
              "Week 02/session-05/Colors",
              "Week 02/session-05/Comments",
              "Week 02/session-05/Inheritance",
              "Week 02/session-05/README",
              "Week 02/session-05/Specificity",
              "Week 02/session-05/animations",
              "Week 02/session-05/fonts",
              "Week 02/session-05/learning-outcomes",
              "Week 02/session-05/morning-challenge",
              "Week 02/session-05/resources",
            ],
          },
        ],
      },
      {
        type: "category",
        label: "Week 3",
        items: [
          "Week 03/README",
          {
            type: "category",
            label: "Session 6",
            items: [
              "Week 03/session-06/Position-workshop",
              "Week 03/session-06/README",
              "Week 03/session-06/assignment",
              "Week 03/session-06/flexbox",
              "Week 03/session-06/layout",
              "Week 03/session-06/learning-outcomes",
              "Week 03/session-06/morning-challenge",
              "Week 03/session-06/resources",
            ],
          },
          {
            type: "category",
            label: "Session 7",
            items: [
              "Week 03/session-07/README",
              "Week 03/session-07/flexbox",
              "Week 03/session-07/learning-outcomes",
              "Week 03/session-07/morning-challenge",
              "Week 03/session-07/resources",
            ],
          },
          {
            type: "category",
            label: "Session 8",
            items: [
              "Week 03/session-08/HTML-project",
              "Week 03/session-08/README",
              "Week 03/session-08/project",
            ],
          },
        ],
      },
      {
        type: "category",
        label: "Week 4",
        items: [
          "Week 04/README",
          {
            type: "category",
            label: "Session 9",
            items: [
              "Week 04/session-09/README",
              "Week 04/session-09/data-types",
              "Week 04/session-09/intro-to-js",
              "Week 04/session-09/learning-outcomes",
              "Week 04/session-09/research-topics",
              "Week 04/session-09/resources",
              "Week 04/session-09/variables-and-constants",
            ],
          },
          {
            type: "category",
            label: "Session 10",
            items: [
              "Week 04/session-10/README",
              "Week 04/session-10/exercise",
              "Week 04/session-10/learning-outcomes",
              "Week 04/session-10/morning-challenge",
              "Week 04/session-10/operators",
              "Week 04/session-10/research-topics",
              "Week 04/session-10/resources",
            ],
          },
          {
            type: "category",
            label: "Session 11",
            items: [
              "Week 04/session-11/README",
              "Week 04/session-11/exercises",
              "Week 04/session-11/functions-scopes",
              "Week 04/session-11/intro-to-functions",
              "Week 04/session-11/learning-outcomes",
              "Week 04/session-11/loops",
              "Week 04/session-11/morning-challenge",
              "Week 04/session-11/research-topics",
              "Week 04/session-11/resources",
              "Week 04/session-11/var-let-const",
            ],
          },
        ],
      },
      {
        type: "category",
        label: "Week 5",
        items: [
          "Week 05/README",
          {
            type: "category",
            label: "Session 12",
            items: [
              "Week 05/session-12/README",
              "Week 05/session-12/exercises",
              "Week 05/session-12/functions-scopes",
              "Week 05/session-12/homework",
              "Week 05/session-12/intro-to-functions",
              "Week 05/session-12/learning-outcomes",
              "Week 05/session-12/loop",
              "Week 05/session-12/morning-challenge",
              "Week 05/session-12/research-topics",
              "Week 05/session-12/resources",
            ],
          },
          {
            type: "category",
            label: "Session 13",
            items: [
              "Week 05/session-13/README",
              "Week 05/session-13/exercises",
              "Week 05/session-13/javascript-objects",
              "Week 05/session-13/learning-outcomes",
              "Week 05/session-13/morning-challenge",
              "Week 05/session-13/puzzle",
              "Week 05/session-13/research-topics",
              "Week 05/session-13/resources",
            ],
          },
          {
            type: "category",
            label: "Session 14",
            items: [
              "Week 05/session-14/README",
              "Week 05/session-14/array-methods",
              "Week 05/session-14/arrays",
              "Week 05/session-14/homework",
              "Week 05/session-14/learning-outcomes",
              "Week 05/session-14/loops",
              "Week 05/session-14/research",
              "Week 05/session-14/resources",
            ],
          },
        ],
      },
      {
        type: "category",
        label: "Week 6",
        items: [
          "Week 06/README",
          {
            type: "category",
            label: "Session 15",
            items: [
              "Week 06/session-15/DOM-manipulations",
              "Week 06/session-15/Dom-Exercises",
              "Week 06/session-15/Intro-to-DOM",
              "Week 06/session-15/README",
              "Week 06/session-15/learning-outcomes",
              "Week 06/session-15/research-topics",
              "Week 06/session-15/resources",
            ],
          },
          {
            type: "category",
            label: "Session 16",
            items: [
              "Week 06/session-16/README",
              "Week 06/session-16/learning-outcomes",
              "Week 06/session-16/local-storage",
              "Week 06/session-16/research-topics",
              "Week 06/session-16/resources",
              "Week 06/session-16/todo-app",
              "Week 06/session-17/README",
            ],
          },
        ],
      },
      "project",
    ],
  },
};
